# Generated by Django 3.1.5 on 2021-03-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210304_2121'),
        ('app', '0002_auto_20210214_1411'),
    ]

    operations = [
    ]
