# Generated by Django 3.1.5 on 2021-03-05 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210305_1625'),
        ('app', '0005_merge_20210304_2217'),
    ]

    operations = [
    ]
