# Generated by Django 3.1.5 on 2021-03-25 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20210305_1649'),
        ('app', '0004_auto_20210310_0053'),
    ]

    operations = [
    ]
